version: '3.4'

services:
  
  catalogdb:
    container_name: catalogdb
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - catalogdbdata:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - posgres_basket:/var/lib/postgresql/data/



  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=ep-shiny-band-axy4qyz8-pooler.c-4.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_MO9KHuN5vIRe;SSL Mode=Require;Trust Server Certificate=true;
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb

  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    ports:
      - "6379:6379"

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=ep-dry-glitter-ax8rohis-pooler.c-4.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_yhtgSu3G0mjb;SSL Mode=Require;Trust Server Certificate=true;
      - ConnectionStrings__Redis=microsmooth-form-wellcrafted-12155.db.redis.io:13962,user=default,password=k3VWyhiOBb46I1odmG9qFN0LQVvLAF3L,ssl=True,abortConnect=False
    ports:
      - "8082:8080"
    depends_on:
      - basketdb
      - redis